# OS
FROM ubuntu:14.04
# COMMAND TO INSTALL JUPYTER NOTEBOOK
RUN apt-get update && \
    apt-get install -y wget bzip2 && \
    wget https://repo.anaconda.com/archive/Anaconda3-2021.11-Linux-x86_64.sh && \
    bash Anaconda3-2021.11-Linux-x86_64.sh -b -p /opt/conda && \
    rm Anaconda3-2021.11-Linux-x86_64.sh && \
    /opt/conda/bin/conda install -y jupyter
# EASY START
CMD ["/opt/conda/bin/jupyter", "notebook", "--ip='*'", "--port=8888", "--no-browser","--allow-root"]

